services:
  database:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - ./database=/var/lib/mysql
    ports:
      - ${MYSQL_PORT}=${MYSQL_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - backend-test
