version: "3.9"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/laravel
    depends_on:
      - mysql
      - php
    networks:
      - laravel
  php:
    build:
      context: php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/laravel
    networks:
      - laravel
  mysql:
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
